package eu.dusansalay.statemachine.common

enum class OrderEvent {
    ORDER_CREATED_WITH_ONLINE_PAYMENT,
    ORDER_CREATED_WITH_OFFLINE_PAYMENT_WITH_ALL_PRODUCTS_IN_STOCK,
    ORDER_CREATED_WITH_OFFLINE_PAYMENT_WITH_SOME_PRODUCTS_OUT_OF_STOCK,
    UNBLOCK_ORDER_WITH_SOME_PRODUCTS_OUT_OF_STOCK,
    ORDER_PAYED_WITH_ONLINE_PAYMENT,
    BLOCK_PAYED_ORDER_WITH_SOME_PRODUCTS_OUT_OF_STOCK,
    GENERATE_LABELS,
    BLOCK_ORDER_WITH_FAILED_LABEL_GENERATION,
    BLOCK_ORDER_WITH_ADDRESS_NOT_AUTHORIZED,
    UNBLOCK_ORDER_WITH_GENERATED_LABELS,
    UNBLOCK_ORDER_WITHOUT_GENERATED_LABELS,
    ORDER_AUTOMATICALLY_CLOSED_AFTER_ONLINE_PAYMENT,
    ORDER_READY_FOR_PROCESS_IN_WAREHOUSE,
    ORDER_ACCEPTED_BY_WAREHOUSE,
    ORDER_DROPPED_BY_WAREHOUSE,

    MANUALLY_BLOCK_ORDER,
}